### ISSUE TITLE
Can't Get Combo View

### ISSUE THREAD

**Issue by mampir** [easyw/kicadStepUpMod#220] opened 2024-05-21 08:44 UTC
Hello,

When I try to `Export 3D Model` or another action, I get the following error log:

<pre>
11:47:29  PoM not present
11:47:29  using 'Part' container and 'Links'
11:47:29  FC Version 021-2
11:47:29  kicad StepUp version 12.0.3
11:47:29  tolerance on vertex applied
11:47:29  applying Materials to Shapes
11:47:29  your home path is /home/mmp
11:47:29  export to STEP False
11:47:29  Running the Python command 'ksuToolsExportModel' failed:
Traceback (most recent call last):
  File "/home/mmp/.local/share/FreeCAD/Mod/kicadStepUpMod/./kicadStepUpCMD.py", line 1289, in Activated
    from kicadStepUptools import routineScaleVRML
  File "/home/mmp/.local/share/FreeCAD/Mod/kicadStepUpMod/./kicadStepUptools.py", line 21737, in <module>
    cv.setFeatures( QtGui.QDockWidget.DockWidgetMovable | QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetClosable )
    ^^^^^^^^^^^^^^

'NoneType' object has no attribute 'setFeatures'
</pre>

I'm using FreeCAD 0.21.2 and KiCadStepUp revision 56df083ae33473b5eb7698307ed181cb5c771032.

**Comment by mampir** [comment] 2024-05-21 09:36
I managed to make the export button work with this ugly thing:

<pre>
diff --git a/kicadStepUptools.py b/kicadStepUptools.py
index 7ae55fe..2d86899 100644
--- a/kicadStepUptools.py
<pre>
+++ b/kicadStepUptools.py
@@ -21732,6 +21732,12 @@ if singleInstance():
         cv = t.findChild(QtGui.QDockWidget, "Model")
         if cv is None:
             cv = t.findChild(QtGui.QDockWidget, "Tree view")
+            if cv is None:
+                cv = [o for o in t.children () if o.objectName () == "Combo View"]
+                if cv:
+                    cv = cv[0]
+                else:
+                    cv = None
     #say( "Combo View" + str(cv))
     ## print( "KSUWidget" + str(wf))        
     cv.setFeatures( QtGui.QDockWidget.DockWidgetMovable | QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetClosable )
</pre>

Should I make a pull request this?

**Comment by easyw** [comment] 2024-05-23 07:24
> Should I make a pull request for this?

yes please

**Comment by mampir** [comment] 2024-05-23 11:23
The pull request is here: https://github.com/easyw/kicadStepUpMod/pull/221

**Comment by easyw** [comment] 2024-05-31 16:58
hi @mampir 
I annot reproduce your issue...
could you please attach a zipped version of your FreeCAD _'user.cfg'_ file?

**Comment by mampir** [comment] 2024-05-31 20:25
[user.cfg.zip](https://github.com/user-attachments/files/15518413/user.cfg.zip)
Here you go. You may also note, that I'm using I'm using this packaging of FreeCAD: https://www.parabola.nu/packages/libre/x86_64/freecad/

**Comment by easyw** [comment] 2024-06-19 07:14
@mampir 
I cannot reproduce your issue...
it could be related to your distribution/packaging...
I'm closing it for the moment

**Closed by easyw** 2024-06-19 07:14 UTC

**Comment by mampir** [comment] 2024-06-19 11:16
That's very disappointing and annoying. Of course it is because of different distribution and packaging - people use more than one distribution and packaging in this world. You could have just implemented the simple fix I already submitted.

**Comment by easyw** [comment] 2024-08-26 15:38
@mampir 
it should be now implemented with https://github.com/easyw/kicadStepUpMod/commit/b5ef27d2f4eaaa4bf60be5339ba7787408462979

**Comment by mampir** [comment] 2024-09-12 20:13
Thank you for implementing this! Unfortunately I'm not sure if this is necessary anymore, because the current version of FreeCAD that I have doesn't have these issues anymore. It seems to the package maintainers applied some patches to FreeCAD which deal with these issues. I think that was done on July 27, but I'm not sure.
